### ISSUE TITLE
Use `user_typing` event instead of hard coded loading message

### ISSUE THREAD

**Issue by homanp** [superagent-ai/slack-bot#9]
# Description

@elisalimli please use https://api.slack.com/events/user_typing instead of hardcoding in `I'm thinking...`. 

![Screenshot 2024-03-14 at 15 43 38](https://github.com/superagent-ai/superagent-slack-bot/assets/2464556/bf03ea93-cd82-46bf-8f6f-e60f9ecbaeba)

**Comment by elisalimli** [comment]
@homanp Right, but that feature is only works with RTM, it's [deprecated](https://api.slack.com/legacy/rtm#:~:text=The%20legacy%20Real%20Time%20Messaging,as%20the%20%22RTM%20API%22.) and we don't use it either.

**Comment by homanp** [comment]
@elisalimli ok, just rename it to `Typing...`
